version: '3.9'
services:
  backend:
    build: .
    ports:
      - "5001:5000"
    env_file:
      - .env
    depends_on:
      - mongo

  mongo:
    image: mongo:7
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
